---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create Cloudtrail Trail

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- Name give to this project
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-code-repos-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$
#      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- SNS Email Notifications
  EmailAddrSNS:
    Description: "Openvpn SNS Email Endpoint"
    ConstraintDescription: "Must be a valid email address"
    Type: String
    Default: "dh.info@posteo.net"
    AllowedPattern:
      ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$

  # ------------------------------------------
  # --- Parameter Value
#  CloudTrailPathParameter:
#    Description: Enter the bucket path for your CloudTrail Logs
#    Type: String
#    Default: '<CloudTrail_BUCKET_NAME>/<PREFIX>/AWSLogs/<ACCOUNT-ID>/CloudTrail/'


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         S3 BUCKET DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- CloudTrail Logs Bucket Definition
  BucketCTrailLogs:
    Type: "AWS::S3::Bucket"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Project"
          Value: !Sub "${ProjectName}"
      # .............................
      BucketName: !Sub "logs.${ProjectName}"
      # .............................
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - 
          ServerSideEncryptionByDefault: 
            SSEAlgorithm: "AES256"

  # ------------------------------------------
  # --- CloudTrail Logs Bucket Policy
  BucketCTrailPolicy:
    # .............................
    Type: "AWS::S3::BucketPolicy"
    # .............................
    Properties:
      # .............................
      Bucket: !Ref BucketCTrailLogs
      PolicyDocument: 
        Version: "2012-10-17"
        Id: "CTrailLogsBucketAccess"
        Statement:
          # ---
          - 
            Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal:
                Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub "arn:aws:s3:::${BucketCTrailLogs}"
          # ---
          - 
            Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal:
                Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${BucketCTrailLogs}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         CLOUDWATCH LOGS DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- Trail Definition
  CWatchLogsGrp:
    Type: "AWS::Logs::LogGroup"
    # .............................
    Properties:
      # .............................
      LogGroupName: !Sub "logs.${ProjectName}"


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         CLOUDTRAIL DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- Trail Definition
  CTrailTrail:
    Type: "AWS::CloudTrail::Trail"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Project"
          Value: !Sub "${ProjectName}"
      # .............................
      TrailName: !Sub "ctrail.${ProjectName}"
      S3BucketName: !Ref BucketCTrailLogs
      # .............................
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      IsLogging: true
      # .............................
      CloudWatchLogsLogGroupArn: !GetAtt CWatchLogsGrp.Arn
      CloudWatchLogsRoleArn: !GetAtt CWatchLogsIamRole.Arn


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         IAM POLICIES & ROLES DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- IAM Role Definition
  CWatchLogsIamRole:
    Type: "AWS::IAM::Role"
    # .............................
    Properties:
      # .............................
      RoleName: !Sub "role.${ProjectName}.cwatch.${AWS::Region}"
      Path: "/service-role/"
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"cloudtrail.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      ManagedPolicyArns: 
        - !Ref CWatchManagedPolicy

  # ------------------------------------------
  # --- IAM Policy Definition
  CWatchManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    # .............................
    Properties:
      # .............................
      ManagedPolicyName: !Sub "service.${ProjectName}.cwatch.${AWS::Region}"
      Path: "/service-role/"
      # .............................
      PolicyDocument: 
        Version: "2012-10-17"
        Id: !Sub "service.${ProjectName}.cwatch"
        Statement:
          # ---
          - Sid: "AWSCloudTrailCreateLogStream"
            Effect: "Allow"
            Action:
              - logs:CreateLogStream
            Resource:
              - !GetAtt CWatchLogsGrp.Arn
          # ---
          - Sid: "AWSCloudTrailPutLogEvents"
            Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource:
              - !GetAtt CWatchLogsGrp.Arn

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         ATHENA DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- IAM Role Definition
  CloudTrailLogsTable:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: default
      Description: Creates CloudTrail Logs Table
      Name: Create Table - CloudTrail Logs
      QueryString: !Sub |
        -
          CREATE EXTERNAL TABLE IF NOT EXISTS cloudtrail_logs (
                eventversion STRING,
                useridentity STRUCT<
                               type:STRING,
                               principalid:STRING,
                               arn:STRING,
                               accountid:STRING,
                               invokedby:STRING,
                               accesskeyid:STRING,
                               userName:STRING,
                sessioncontext:STRUCT<
                attributes:STRUCT<
                               mfaauthenticated:STRING,
                               creationdate:STRING>,
                sessionissuer:STRUCT<  
                               type:STRING,
                               principalId:STRING,
                               arn:STRING, 
                               accountId:STRING,
                               userName:STRING>>>,
                eventtime STRING,
                eventsource STRING,
                eventname STRING,
                awsregion STRING,
                sourceipaddress STRING,
                useragent STRING,
                errorcode STRING,
                errormessage STRING,
                requestparameters STRING,
                responseelements STRING,
                additionaleventdata STRING,
                requestid STRING,
                eventid STRING,
                resources ARRAY<STRUCT<
                               ARN:STRING,
                               accountId:STRING,
                               type:STRING>>,
                eventtype STRING,
                apiversion STRING,
                readonly STRING,
                recipientaccountid STRING,
                serviceeventdetails STRING,
                sharedeventid STRING,
                vpcendpointid STRING
                )
                PARTITIONED BY (region string, year string, month string, day string)
                ROW FORMAT SERDE 'com.amazon.emr.hive.serde.CloudTrailSerde'
                STORED AS INPUTFORMAT 'com.amazon.emr.cloudtrail.CloudTrailInputFormat'
                OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
                LOCATION 's3://${CloudTrailPathParameter}'

  CloudTrailPartition:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: default
      Description: Creates CloudTrail Partitions
      Name: Create Partition - CloudTrail
      QueryString: !Sub
        |-
          ALTER TABLE cloudtrail_logs ADD 
              PARTITION (region='us-east-1',
                         year='2020',
                         month='11',
                         day='23')
              LOCATION 's3://${CloudTrailPathParameter}us-east-1/2020/11/23/'

# ==========================================
Outputs: {}
# Outputs:
